### ISSUE TITLE
Perfect with a tiny problem

### ISSUE THREAD

**Issue by KatkayApps** [JimmXinu/EpubMerge#1]
Hi there, EpubMerge is fantastic, thanks but there is a tiny little problem

I have 10 books that were exported from Pages with fixed layout, in that case, portrait.

I import all 10 books on EpubMerge and the merged result is reflowable layout. 

I would like to make EpubMerge follow the layout of the files it is merging but the result is always reflowable.

Is there any way to force fixed layout portrait? Thanks

**Comment by JimmXinu** [comment]
Can you attach a couple before and after epubs that demonstrate the issue?  IE, a couple of epubs pre-merge and the merged result?

**Comment by JimmXinu** [comment]
No response from reporter.
