### ISSUE TITLE
Comics get smaller when merged

### ISSUE THREAD

**Issue by dl0096** [JimmXinu/EpubMerge#11]
I merged about 100 chapters of a manga into one and when reading on the kindle, there's a lot of white space around the actual content, which doesn't exist to the same extent if I read the individual chapters themselves.

**Comment by JimmXinu** [comment]
EpubMerge doesn't change anything in the HTML pages themselves, it just makes the metadata files that include them in the merged epub.

Without seeing the epubs for myself (before and after), I don't know what's going on.  Can you duplicate the issue with a small sample set?
