### ISSUE TITLE
Kindle Previewer doesn't accept merged EPUBs

### ISSUE THREAD

**Issue by ziaa-xyz** [JimmXinu/EpubMerge#12]
The plugin works great and online .epub readers perfectly open the files.
Only thing is that I want to use this files on my Kindle which afaik wants .kpf?
The Kindle Previewer software give the following error: 
Type | Description 
Error | E23005: Language not specified in   metadata. The dc:Language field is mandatory. Aborting.
Status | Book conversion failed.

Is there anything I can do or change in metadata to fix this perhaps? The dc:Language field is present, so i don't see the issue

**Comment by JimmXinu** [comment]
EpubMerge adds a `dc:language` tag for each source book's language as set in Calibre.  If none of the source books have a language set, then the merged book will not have and `dc:language` tags.

Personally, I convert epub to azw3 format in Calibre for use on Kindle without any issues.
