### ISSUE TITLE
"File as" title and author fields

### ISSUE THREAD

**Issue by kingjon3377** [JimmXinu/EpubMerge#13]
When I convert almost any EPUB (including those produced by FanFicFare) to Kindle format and put it on my Kindle, and sort the list by title, if the title begins with "A" or "The" the list does "title sorting". (For instance, "The Princess and the Goblin" would come between "Pride and Prejudice" and "Sense and Sensibility".) And in many cases a "sort by author" list sorts by author last name (when such names are multiple words, so "George MacDonald" would come after "Jane Austen").

But when I use this script (from the CLI) to merge multiple EPUBs from a single author, with an explicitly specified title beginning with "A" or "The", that merged ebook is alphabetized on the Kindle under "A" or "The", rather than the first non-article word as the unmerged books are. 

I did some investigating, and found that one ebook where the title sorts properly has `<dc:language>en</dc:language>` in its OPF file, while one not-properly-sorting ebook that had been produced by EpubMerge didn't have any such tag. And for the author name, in some EPUBs I more-or-less "hand-assemble" from HTML files, I've used [the `file-as` attribute on the `aut` creator property](https://idpf.org/epub/20/spec/OPF_2.0_final_spec.html#Section2.2.2) to get the ebooks to sort properly. (I found [some documentation](https://www.w3.org/TR/epub-33/#sec-file-as) that suggests the `file-as` attribute would be valid on a title as well, but I don't know if it would actually have any effect.)

The simplest approach I would suggest is to copy the `dc:language` property into the nested OPF if it is present, with only a single shared value, in either any or all of the input EPUBs' OPFs, and preserve the `file-as` attribute on the author-name property if shared by all the input EPUBs (as I believe the script does with the "for display" author name). But some way of specifying either these specific properties, or any arbitrary additional metadata, from the command line might also be helpful.

**Comment by JimmXinu** [comment]
```

**Comment by JimmXinu** [comment]
`-l` / `--language` is already a CLI option.  Although I admit it didn't apply `en` by default as the help text states.  I've pushed that change up.
```
$ epubmerge.py
Usage: python epubmerge.py [options] <input epub> [<input epub>...]

Given list of epubs will be merged together into one new epub.


Options:
  -h, --help            show this help message and exit
  -o OUTPUT, --output=OUTPUT
                        Set OUTPUT file, Default: merge.epub
  -t TITLE, --title=TITLE
                        Use TITLE as the metadata title.  Default: '<first
                        epub title> Anthology'
  -d DESC, --description=DESC
                        Use DESC as the metadata description.  Default: '<epub
                        title> by <author>' for each epub.
  --debug               Show debug and notice output.
  -a AUTHOR, --author=AUTHOR
                        Use AUTHOR as a metadata author, multiple authors may
                        be given, Default: <All authors from epubs>
  -g TAG, --tag=TAG     Include TAG as dc:subject tag, multiple tags may be
                        given, Default: None
  -l LANG, --language=LANG
                        Include LANG as dc:language tag, multiple languages
                        may be given, Default: en
  -n, --no-titles-in-toc
                        Default is to put an entry in the TOC for each epub,
                        nesting each epub's chapters under it.
  -N, --no-original-toc
                        Default is to include the TOC from each original epub.
  --keep-single-tocs    Default is to add only epub title to TOC if there is
                        only 1(or 0) entries in input TOC.  Does not apply if
                        using --no-titles-in-toc
  -f, --flatten-toc     Flatten TOC down to one level only.
  -c COVER, --cover=COVER
                        Path to a jpg to use as cover image.
  -k, --keep-meta       Keep original metadata files in merged epub.  Use for
                        UnMerging.
  -s URL, --source=URL  Include URL as dc:source and
                        dc:identifier(opf:scheme=URL).
  -u, --unmerge         UnMerge an existing epub that was created by merging
                        with --keep-meta.
  -D OUTPUTDIR, --outputdir=OUTPUTDIR
                        Set output directory for unmerge, Default: (current
                        dir)
```

I will also look into keeping `file-as` attribute on authors.

I'm not interested in trying to allow arbitrary metadata from EM--there's just too many options.

**Comment by kingjon3377** [comment]
> `-l` / `--language` is already a CLI option

Ah, thank you; when I started debugging at the `epubmerge` command-line level that didn't look relevant, and then by the time I got down into the details of the metadata fields I'd forgotten it was mentioned in the `--help` listing.

**Comment by JimmXinu** [comment]
I've pushed a version that uses `opf:file-as` attrs from `<dc:creator [opf:role"="aut]"` tags.  Let me know if this meets your needs.

Note this is only used with CLI and only when author(s) have _not_ been specified with `-a`/`--author`.

I suspect the reason this hasn't come up before is because the majority are using the Calibre plugin version and Calibre injects its metadata info automatically whenever an ebook is sent to a device.
