### ISSUE TITLE
Not installable

### ISSUE THREAD

**Issue by Spixmaster** [JimmXinu/EpubMerge#14]
I would like to install the programme with the usual commands `python -m build -nw` and `python -m installer /path/to/dist/*.whl `. Currently, this is not possible. https://github.com/JimmXinu/EpubMerge/issues/5 is related.

I packaged it for [Arch Linux](https://aur.archlinux.org/packages/epubmerge) and the current way the installation needs to be handled is unusual.

**Comment by JimmXinu** [comment]
There's no real building to be done, but I'd accept a PR to add that.

**Comment by Spixmaster** [comment]
Is there anything that needs to be considered for it being a Calibre plugin? Something like a certain file in the root directory?

**Comment by JimmXinu** [comment]
Calibre plugin distro is a separate manual process.  `epubmerge.py` is all that's needed for CLI, other files are all for plugin.

**Comment by JimmXinu** [comment]
Addressed in #16, thanks @Spixmaster .
