### ISSUE TITLE
PDF+EPUB merge

### ISSUE THREAD

**Issue by andradadad** [JimmXinu/EpubMerge#15]
Any suggestions?

Could end on any format.

**Comment by JimmXinu** [comment]
I would explore using Calibre's Convert feature to make the PDF into an epub to use with EpubMerge; or conversely, convert the epub to PDF and use pdfcat or something like it to concatenate.  PDFs can be difficult to convert to other formats.

Regardless, this isn't a code issue with EpubMerge.
