### ISSUE TITLE
hope can have more option for merge file

### ISSUE THREAD

**Issue by bluelovers** [JimmXinu/EpubMerge#2]
1. merge file in epub if they are same content
2. merge file structures

current
```
1/img/p001.jpg
1/img/p002.jpg
1/css/style.css
2/img/p001.jpg
2/img/p003.jpg
2/css/style.css // same content with 1/css/style.css
```
to
```
img/1/p001.jpg
img/1/p002.jpg
img/2/p001.jpg
img/2/p003.jpg
css/style.css
```

**Comment by JimmXinu** [comment]
EpubMerge is a tool for merging epubs with as little change to the source content as possible.  I'm not interested in arbitrarily changing the file structures--the book readers don't care what the structure is.

Detecting duplicate files and saving only one copy would be nice, but again, it would require making more changes to the source files than I'm interested in doing.
