### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [JimmXinu/EpubMerge#5]
https://pypi.org/project/EpubMerge/ is 404.  Is this package on PyPI?

It is one of handful of packages in openSUSE that do not appear to be on PyPI.
https://repology.org/project/python:epubmerge/versions

**Comment by JimmXinu** [comment]
EpubMerge does not have a PyPi package.  I started setting it up once, but stopped for... reasons?  Probably didn't want to deal with py2 vs py3 at the time.  Really, it's a lot more useful as a Calibre Plugin than as a CLI.

If you personally would use an EpubMerge CLI, I'll put it on my list to come back to.  But not if it's just for completionism.

As for openSUSE, I cannot take responsibility for what downstream packagers may do.

**Comment by kingjon3377** [comment]
I would personally use an EpubMerge CLI; I use FanFicFare only as a CLI, and I only use Calibre's `ebook-convert` and `ebook-viewer` commands, not the collection manager itself.

(I've in fact started trying to write a Gentoo ebuild to turn the source from the release snapshot tarball into a form I can install and use from the command line, but very quickly ran into the problem that `epubmerge/__init__.py` refers to a Calibre-internal class that's not installed to anywhere on the PYTHONPATH ...)

It doesn't matter to me whether it's on PyPI or not, so long as there's some way to get a usable and installable CLI script.

**Comment by JimmXinu** [comment]
[epubmerge.py](https://github.com/JimmXinu/EpubMerge/blob/main/epubmerge.py) can be downloaded and run CLI by itself.  `-h` to see the options.

I haven't done more than cursory testing of it in a long time, but I don't know of any reason why it shouldn't still work.

**Comment by kingjon3377** [comment]
Thanks! That works. I started with trying to make my ebuild install the whole thing, and so ignored the obvious ... 

Maybe make the README explain that `epubmerge.py` can be run from the command line without any special setup, though? After writing an ebuild for (the CLI part of) FanFicFare I was primed to expect the CLI to be more complicated.

**Comment by NightMachinary** [comment]
Can this be turned into a proper package? It would be easier to use then.
