### ISSUE TITLE
ERROR: Cannot Merge Epubs

### ISSUE THREAD

**Issue by saghiransari** [JimmXinu/EpubMerge#6]
Not able to merge ePub file.#Error It says your file is ePub3 but EpubMerge only supports ePub2. However I've merged same file 2 days ago I worked perfectly. But not now it's not working.

**Comment by JimmXinu** [comment]
I'd have to see the epub in question to help you.  Can you attach it or post a URL?

**Comment by ranka47** [comment]
I am also getting the same issue. The ePub I am trying on are from this URL, https://www.upschub.com/download-ncert-books-epub-edition/

It fails at https://github.com/JimmXinu/EpubMerge/blob/406bb866f3dd1f450df23eebd1cb75f3a7b1dabc/epubmerge_plugin.py#L648

Is support for epub3 not available? Any workaround for that?

**Comment by JimmXinu** [comment]
That's exactly what the error message means.  EpubMerge doesn't support EPUB3 at this time.

But it's trivial to use Calibre's Convert feature to convert to EPUB3->EPUB2 (it's on the EPUB output option).

I tried a random sample from your link and after converting to epub2, they merged fine.
