### ISSUE TITLE
Merging Manga in EPUB format crops the images (pages) at the top and bottom of the page. (Kobo Libra 2.0)

### ISSUE THREAD

**Issue by scrubadubud** [JimmXinu/EpubMerge#7]
NOTE: Manga size before using EpubMerge is 1264 x 1680, I believe it's being changed to 1200x1600 After being merged with EpubMerge: 
<img width="1280" alt="Screenshot 2022-01-17 084422" src="https://user-images.githubusercontent.com/69694188/149782108-f3c09728-4728-43ee-a518-5c0e20076140.png">

I have an issue where merging manga with EpubMerge causes the images to crop (not resize) at the top and bottom of the pages, leading to occasionally missing important dialogue.

What it looks like after using EpubMerge:
![Merged](https://user-images.githubusercontent.com/69694188/149781572-deb409eb-2603-4f66-a1e6-fb33b66f2940.jpg)

My conversion process: 

Folder of images => .zip file => .zip file to Epub with KCC (kindle comic converter) => Repeat for all manga volumes until all volumes are converted to EPUB.

Manga volumes (now EPUBs) to Calibre => Sort by title => Epub merge (no metadata changes other than author name).

(Please note that before merging with Calibre, the pages are the correct size and don't get cropped at all, I've tested it.)

What it looks like without using EpubMerge:
![NotMerged](https://user-images.githubusercontent.com/69694188/149781518-a40ce4d7-2cc4-4b75-8f84-bb24b303e39e.jpg)

**Comment by JimmXinu** [comment]
Your first image is a Calibre cover image--Calibre generates them at 1200x1600 by default.  Doesn't have anything to do with the size of images inside the epub.

EpubMerge doesn't do any image processing.  It basically only manipulates the zip file (epub) and XML (metadata) contents.

But it's entirely possible that a manga epub has additional or different metadata settings than EpubMerge uses that make a difference.

I need to see some of the actual epub files before (and after) merging to tell you anything more.

**Comment by scrubadubud** [comment]
> Your first image is a Calibre cover image--Calibre generates them at 1200x1600 by default. Doesn't have anything to do with the size of images inside the epub.

Thanks for clarifying.

> I need to see some of the actual epub files before (and after) merging to tell you anything more.
I'm going to merge two chapters and do just that.

Disclaimer, I chose the start of berserk as it what was easiest, though the first few pages are slightly NSFW.
Also, Github wasn't letting me post .zip even though it's supported... So I used mediafire: https://www.mediafire.com/file/vmmjvpsxqkkbm8g/Berserk.zip/file

**Comment by JimmXinu** [comment]
For the record, the image in the first post (0009-kcc) appears to be shifted down--there's missing image at the bottom, but not the top, where there's extra space.

You are inputting epub3 files.  EpubMerge doesn't natively deal with epub3--it calls Caliber's Convert feature in the background to get epub2 files that it then merges.

Convert re-writes all the CSS & xhtml files and, by default, resizes the images.  [This](https://ebooks.stackexchange.com/questions/8303/how-to-not-have-calibre-reduce-pictures-resolution-when-converting-from-epub-o) (somewhat old) stackexchange answer says that is controlled by the output profile setting.

Changing the default value for output profile in Calibre doesn't seem to change it for the background CLI(ish) way EpubMerge calls it.  However, I can explicitly call it with output profile 'tablet' so it doesn't resize images.

At that point, the images are unchanged, but the CSS and xhtml are still subtly different.  The only real difference I see between the two is the converted version also applies a 5pt left and right margin to the `<body>` tag.  But ebook readers are known to be finicky.

I've pushed the change for the output format(c922a107e4e7788e5b9b1e1d7ad6da2dedfa778f) and [posted a test version](https://www.mobileread.com/forums/showthread.php?p=4190506#post4190506) with that change.

Please try again with the test version and let me know.

**Comment by scrubadubud** [comment]
You're the best! Thanks for helping :)

I'll let you know if I run into any issues.

**Comment by scrubadubud** [comment]
There's no visible difference sadly:
![Merged after test](https://user-images.githubusercontent.com/69694188/149867502-646462cd-0845-45ae-9da6-4b11cc551afb.jpg)
Here's the updated Epubs:
https://www.mediafire.com/file/dza9l1nqi0syc9c/AfterTest.zip/file
It's possibly just a Kobo issue, though the mangas/comics have no issue before they're merged.

**Comment by scrubadubud** [comment]
> For the record, the image in the first post (0009-kcc) appears to be shifted down--there's missing image at the bottom, but not the top, where there's extra space.
> 
> You are inputting epub3 files. EpubMerge doesn't natively deal with epub3--it calls Caliber's Convert feature in the background to get epub2 files that it then merges.
> 
> Convert re-writes all the CSS & xhtml files and, by default, resizes the images. [This](https://ebooks.stackexchange.com/questions/8303/how-to-not-have-calibre-reduce-pictures-resolution-when-converting-from-epub-o) (somewhat old) stackexchange answer says that is controlled by the output profile setting.
> 
> Changing the default value for output profile in Calibre doesn't seem to change it for the background CLI(ish) way EpubMerge calls it. However, I can explicitly call it with output profile 'tablet' so it doesn't resize images.
> 
> At that point, the images are unchanged, but the CSS and xhtml are still subtly different. The only real difference I see between the two is the converted version also applies a 5pt left and right margin to the `<body>` tag. But ebook readers are known to be finicky.
> 
> I've pushed the change for the output format([c922a10](https://github.com/JimmXinu/EpubMerge/commit/c922a107e4e7788e5b9b1e1d7ad6da2dedfa778f)) and [posted a test version](https://www.mobileread.com/forums/showthread.php?p=4190506#post4190506) with that change.
> 
> Please try again with the test version and let me know.

Just to confirm I installed in correctly, the version is 2.11.2 right?

**Comment by JimmXinu** [comment]
Yes, EpubMerge v2.11.2 is the test version I posted.

In that case, I don't have an immediate EpubMerge solution for you.  I do have some ideas you can try, though:

~~Can KCC output epub2?~~ No, KCC (kindle comic converter) says epub3 and doesn't appear to have an epub2 option.  A quick look in their code agrees.

KCC output is, however, epub2 compatible (it still has the toc.ncx file from epub2).

Attached is a test version of the plugin (still marked v2.11.2) that does *not* do the epub3->epub2 conversion and instead relies on the input epubs being at least epub2 compatible.
[EpubMerge.zip](https://github.com/JimmXinu/EpubMerge/files/7890502/EpubMerge.zip)  
 
Please give it a try and let me know how it goes.

**Comment by JimmXinu** [comment]
You might also try manually converting the merged epub to epub3--Kobo may just prefer it.

**Comment by scrubadubud** [comment]
Update: I discovered a way to generate volumes together with KCC, which eliminates the need for EpubMerge, though since this is still an issue others will encounter I will continue debugging with you.

I'll respond with my tests soon.

**Comment by scrubadubud** [comment]
> Update: I discovered a way to generate volumes together with KCC [See Reddit Link](https://www.reddit.com/r/kobo/comments/s64u6w/im_crossposting_this_if_anyone_here_has_a_similar/) which eliminates the need for EpubMerge, though since this is still an issue others will encounter I will continue debugging with you.
> 
> I'll respond with my tests soon.

I also discovered that Epub files larger than ~1.5 gbs will cause the Kobo Firmware to think the file is DRM protected, when it's not.

**Comment by scrubadubud** [comment]
Doesn't seem to have done much except removing the black bar at the top of the image.

Results (Without manual convert to Epub3)
![Epub2](https://user-images.githubusercontent.com/69694188/150153084-92bdc16c-aa19-4528-a537-35abac8e5657.jpg)
Results (after converting to Epub3)
![Epub3](https://user-images.githubusercontent.com/69694188/150153144-f4e22920-46f0-41be-9a7f-34227b7adf68.jpg)
Results (Avoiding EpubMerge Entirely, and making a 1.4gb Epub file with KCC)
![KCC BULK](https://user-images.githubusercontent.com/69694188/150153292-41df4c76-0cba-40ec-a66a-175cc3cef2f8.jpg)
Here are my KCC settings:
![image](https://user-images.githubusercontent.com/69694188/150153518-ef6a9b01-b243-4c11-93f3-baa4a4490b5c.png)

Your change does remove the odd black bar it seems.

[Used 4 chapters this time](https://www.mediafire.com/file/z7eysxzhbo9gxea/Testing+files.zip/file)

**Comment by JimmXinu** [comment]
There are a few metadata settings in `content.opf` from KCC that EpubMerge doesn't keep that may be key.  Notably:
```
    <meta property="rendition:orientation">portrait</meta>
    <meta property="rendition:spread">portrait</meta>
    <meta property="rendition:layout">pre-paginated</meta>
```
They appear to be epub3 specific.

I'm not seeing this issue with any device I've tried with the EpubMerge output.  

And since you've come up with a solution (use KCC for all at once), I'm inclined to declare it a known corner case EpubMerge doesn't handle perfectly and ignore it.

**Comment by scrubadubud** [comment]
Alright, thanks for your help!

Wish you the best.
